### ISSUE TITLE
Do Dates Matter?

### ISSUE THREAD

**Issue by lmstearn** [danrue/oh_my_fortune#1]
Hey DanRue!
[This fortune file](https://github.com/danrue/oh_my_fortune/blob/master/1985/03) comes from 1985, but at the bottom there is:

> Rush Limbaugh's 35 Undeniable Truths of Life:

> (6)  Ours is a world governed by the aggressive use of force.

>  "The Limbaugh Letter," Copyright 1992, EFM Publishing, Inc.

It's possible the "1992" might have been added later.

Reason is I'm trying to date and author the following:

> Fifty flippant frogs Walked by on flippered feet And with their slime they made the time Unnaturally fleet.

Google gives around 1990, but if it was 1985, that's a big difference!
Thanks. :)

**Comment by danrue** [comment]
Hi! Thank you for the interesting distraction this morning.

First, these fortune files in this repository are not authoritative in any way. Second, they unrelated to one another, and so the date of Limbaugh's quote has nothing to do with the other quotes in the file.

The source material comes from freebsd. Specifically, before the great fortune purges of 2013 and 2017 (see https://github.com/koitsu/fortune-mod-freebsd-classic for some of the history there).

The 'Fifty flippant frogs' quote was originally added to FreeBSD on September 3rd, 1994, by Jordan Hubbard - https://github.com/freebsd/freebsd/commit/057afceb86e030ad65b0130436860d9a18066186

That doesn't help us, because it was imported from 4.4 BSD. You can see it in the 4.4 tree @ https://github.com/sergev/4.4BSD-Lite2/blob/master/usr/src/games/fortune/datfiles/fortunes#L3957, but I don't know if actual commit history exists for it, or where to find it...

**Comment by danrue** [comment]
@lmstearn I love your website!

**Comment by danrue** [comment]
@lmstearn I also realized another misunderstanding. Please disregard that the fortune file was made in 1985 - that date is fiction. This quote also appears in years 1971, and 2026, for example... I'm sorry for the confusion this may have caused.

**Comment by lmstearn** [comment]
Gotcha.
Have an old 1990 fortune file myself- (well 99% sure it's 1990) entitled **!07/11 PDP a ni deppart m'I !**.
It's got a lotta stuff which is repro'd in yours, including the above quote- but for the interesting fact that a "%" separator is used instead of line feed. Might have been a porting error- who knows?
Edit: Ehm- the (rather messed up) file has this date inserted randomly in the 2001 penguin story: 

> As the aircraft approached. 2001-02-02: For five weeks. the birds went quiet and stopped calling... 

It's been obviously edited or overwritten since 1990. (sigh) we'll never know.
...
Your [website article](https://therub.org/2014/09/30/2014-guide-to-a-personal-website/) is interesting- perhaps something like that here on Github so we can star it!

**Comment by danrue** [comment]
Hi @lmstearn - A friend found the first occurrence of the 'flippant frog' quote at  https://github.com/csrg/original-bsd/commit/e1a75375eb41fb43e96e76f9b963ef513b05859f

It looks like the quote is at least as old as Sep 8, 1989.

Note also that the files in this repo aren't fortune files and the dates on the files don't mean anything. I'm sorry for the confusion.
